// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../../internal/app/models.js";

/**
 * @returns {$CancellablePromise<void>}
 */
export function ConfirmClose() {
    return $Call.ByID(1472773685);
}

/**
 * @param {app$0.GlobalConfigurationDraft} global
 * @param {app$0.UploaderEditorDraft} uploader
 * @returns {$CancellablePromise<app$0.DesktopStartupState>}
 */
export function CreateInitialConfigurationSet(global, uploader) {
    return $Call.ByID(990985889, global, uploader);
}

/**
 * @param {app$0.ShortenerDeleteDraft} draft
 * @returns {$CancellablePromise<app$0.ShortenerEditorState>}
 */
export function DeleteShortener(draft) {
    return $Call.ByID(1076607812, draft);
}

/**
 * @param {app$0.UploaderDeleteDraft} draft
 * @returns {$CancellablePromise<app$0.UploaderEditorState>}
 */
export function DeleteUploader(draft) {
    return $Call.ByID(444550388, draft);
}

/**
 * @returns {$CancellablePromise<app$0.GlobalConfigurationEditorState>}
 */
export function LoadGlobalConfigurationEditor() {
    return $Call.ByID(571400281);
}

/**
 * @param {app$0.RepairDocumentKind} kind
 * @returns {$CancellablePromise<app$0.RepairDocumentState>}
 */
export function LoadRepairDocument(kind) {
    return $Call.ByID(94730249, kind);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<app$0.ShortenerEditorState>}
 */
export function LoadShortenerEditor(name) {
    return $Call.ByID(1306663908, name);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<app$0.UploaderEditorState>}
 */
export function LoadUploaderEditor(name) {
    return $Call.ByID(1823470554, name);
}

/**
 * @param {app$0.ShortenerRenameDraft} draft
 * @returns {$CancellablePromise<app$0.ShortenerEditorState>}
 */
export function RenameShortener(draft) {
    return $Call.ByID(3998212323, draft);
}

/**
 * @param {app$0.UploaderRenameDraft} draft
 * @returns {$CancellablePromise<app$0.UploaderEditorState>}
 */
export function RenameUploader(draft) {
    return $Call.ByID(134924561, draft);
}

/**
 * @param {app$0.GlobalConfigurationDraft} draft
 * @returns {$CancellablePromise<app$0.GlobalConfigurationEditorState>}
 */
export function SaveGlobalConfiguration(draft) {
    return $Call.ByID(360515327, draft);
}

/**
 * @param {app$0.RepairDocumentDraft} draft
 * @returns {$CancellablePromise<app$0.DesktopStartupState>}
 */
export function SaveRepairDocument(draft) {
    return $Call.ByID(2828930284, draft);
}

/**
 * @param {app$0.ShortenerEditorDraft} draft
 * @returns {$CancellablePromise<app$0.ShortenerEditorState>}
 */
export function SaveShortenerEditor(draft) {
    return $Call.ByID(4011277875, draft);
}

/**
 * @param {app$0.UploaderEditorDraft} draft
 * @returns {$CancellablePromise<app$0.UploaderEditorState>}
 */
export function SaveUploaderEditor(draft) {
    return $Call.ByID(679003011, draft);
}

/**
 * @param {boolean} dirty
 * @returns {$CancellablePromise<void>}
 */
export function SetGlobalConfigurationDirty(dirty) {
    return $Call.ByID(2317002498, dirty);
}

/**
 * @returns {$CancellablePromise<app$0.DesktopStartupState>}
 */
export function StartupState() {
    return $Call.ByID(1955640671);
}
