// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    DesktopStartupMode,
    RepairDocumentKind
} from "./models.js";

import * as $models from "./models.js";

/**
 * @typedef {$models.DesktopStartupState} DesktopStartupState
 */

/**
 * @typedef {$models.GlobalConfigurationDraft} GlobalConfigurationDraft
 */

/**
 * @typedef {$models.GlobalConfigurationEditorState} GlobalConfigurationEditorState
 */

/**
 * @typedef {$models.RepairDocumentDraft} RepairDocumentDraft
 */

/**
 * @typedef {$models.RepairDocumentState} RepairDocumentState
 */

/**
 * @typedef {$models.ShortenerDeleteDraft} ShortenerDeleteDraft
 */

/**
 * @typedef {$models.ShortenerEditorDraft} ShortenerEditorDraft
 */

/**
 * @typedef {$models.ShortenerEditorState} ShortenerEditorState
 */

/**
 * @typedef {$models.ShortenerRenameDraft} ShortenerRenameDraft
 */

/**
 * @typedef {$models.ShortenerRequestDraft} ShortenerRequestDraft
 */

/**
 * @typedef {$models.UploaderDeleteDraft} UploaderDeleteDraft
 */

/**
 * @typedef {$models.UploaderEditorDraft} UploaderEditorDraft
 */

/**
 * @typedef {$models.UploaderEditorState} UploaderEditorState
 */

/**
 * @typedef {$models.UploaderExtractorDraft} UploaderExtractorDraft
 */

/**
 * @typedef {$models.UploaderMapEntry} UploaderMapEntry
 */

/**
 * @typedef {$models.UploaderRenameDraft} UploaderRenameDraft
 */

/**
 * @typedef {$models.UploaderRequestDraft} UploaderRequestDraft
 */

/**
 * @typedef {$models.UploaderResponseDraft} UploaderResponseDraft
 */
