// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * @readonly
 * @enum {string}
 */
export const DesktopStartupMode = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    DesktopStartupNormal: "normal",
    DesktopStartupSetup: "setup",
    DesktopStartupRepair: "repair",
};

/**
 * @typedef {Object} DesktopStartupState
 * @property {DesktopStartupMode} mode
 * @property {string} configurationPath
 * @property {string} defaultUploader
 * @property {string} defaultShortener
 * @property {boolean} copyToClipboard
 * @property {string[] | null} uploaders
 * @property {string[] | null} shorteners
 * @property {boolean} shortenersPresent
 * @property {string} diagnostic
 */

/**
 * @typedef {Object} GlobalConfigurationDraft
 * @property {string} revision
 * @property {string} defaultUploader
 * @property {string} defaultShortener
 * @property {boolean} copyToClipboard
 */

/**
 * @typedef {Object} GlobalConfigurationEditorState
 * @property {string} configurationPath
 * @property {string} revision
 * @property {string} defaultUploader
 * @property {string} defaultShortener
 * @property {boolean} copyToClipboard
 * @property {string[] | null} uploaders
 * @property {string[] | null} shorteners
 * @property {boolean} shortenersPresent
 */

/**
 * @typedef {Object} RepairDocumentDraft
 * @property {RepairDocumentKind} kind
 * @property {string} revision
 * @property {string} content
 */

/**
 * @readonly
 * @enum {string}
 */
export const RepairDocumentKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    RepairGlobalConfiguration: "config",
    RepairUploaders: "uploaders",
    RepairShorteners: "shorteners",
};

/**
 * @typedef {Object} RepairDocumentState
 * @property {RepairDocumentKind} kind
 * @property {string} path
 * @property {string} revision
 * @property {string} content
 * @property {boolean} present
 */

/**
 * @typedef {Object} ShortenerDeleteDraft
 * @property {string} revision
 * @property {string} name
 */

/**
 * @typedef {Object} ShortenerEditorDraft
 * @property {string} revision
 * @property {string} originalName
 * @property {string} name
 * @property {ShortenerRequestDraft} request
 * @property {UploaderResponseDraft} response
 */

/**
 * @typedef {Object} ShortenerEditorState
 * @property {string} configurationPath
 * @property {boolean} present
 * @property {string} revision
 * @property {string} defaultShortener
 * @property {string[] | null} shorteners
 * @property {ShortenerEditorDraft} draft
 */

/**
 * @typedef {Object} ShortenerRenameDraft
 * @property {string} revision
 * @property {string} originalName
 * @property {string} newName
 */

/**
 * @typedef {Object} ShortenerRequestDraft
 * @property {string} method
 * @property {string} url
 * @property {UploaderMapEntry[] | null} headers
 * @property {UploaderMapEntry[] | null} query
 * @property {string} dataJSON
 */

/**
 * @typedef {Object} UploaderDeleteDraft
 * @property {string} revision
 * @property {string} name
 */

/**
 * @typedef {Object} UploaderEditorDraft
 * @property {string} revision
 * @property {string} originalName
 * @property {string} name
 * @property {UploaderRequestDraft} request
 * @property {UploaderResponseDraft} response
 */

/**
 * @typedef {Object} UploaderEditorState
 * @property {string} configurationPath
 * @property {string} revision
 * @property {string} defaultUploader
 * @property {string[] | null} uploaders
 * @property {UploaderEditorDraft} draft
 */

/**
 * @typedef {Object} UploaderExtractorDraft
 * @property {string} type
 * @property {string} path
 * @property {string} header
 * @property {string} pattern
 * @property {string} group
 */

/**
 * @typedef {Object} UploaderMapEntry
 * @property {string} key
 * @property {string} value
 * @property {boolean} sensitive
 */

/**
 * @typedef {Object} UploaderRenameDraft
 * @property {string} revision
 * @property {string} originalName
 * @property {string} newName
 */

/**
 * @typedef {Object} UploaderRequestDraft
 * @property {string} method
 * @property {string} url
 * @property {UploaderMapEntry[] | null} headers
 * @property {UploaderMapEntry[] | null} query
 * @property {string} body
 * @property {string} fileField
 * @property {UploaderMapEntry[] | null} fields
 * @property {string} dataJSON
 */

/**
 * @typedef {Object} UploaderResponseDraft
 * @property {UploaderExtractorDraft} url
 * @property {UploaderExtractorDraft | null} error
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
